### PR TITLE
Fix execution handling

### LINKED ISSUE #69: Extensions reads a process crashing as a failed proof
There are instances when the child process run by the extension to run kani crashes due to issuing a broken command or other reasons. When this happens, the extension seems to be reading it as a proof failing. 

Screenshot or description of the issue: 

image

I expected to see this happen: 

1. Communication to the user that an underlying process has failed or crashed.
2. No error or "diff" message shown to the user (which is the same UI used for failed proofs). The user should be able to visually be able to distinguish between kani running right, and a proof failing and kani itself failing and the extension failing.

Instead, this happened: *explanation*

Link to PR / commit where the action failed: *link*

### PR DESCRIPTION
**Pull request by jaisnan**
### Description of changes: 

There are instances when the child process run by the extension to run Kani crashes due to issuing a broken command or other reasons. When this happens, the extension seems to be reading it as a proof failing.

Before -
image

After -

Screen Shot 2023-05-18 at 3 32 08 PM

It adds the following changes - 

1. Communication to the user that an underlying process has failed or crashed. Followed by a report issue button which helps the user record the issue with kani-extension.
2. Adds a errored window, which is different than the failed proof window. The icon for the errored proof is different too in the testing panel, which helps distinguish it from proofs that failed.

### Resolved issues:

Resolves #69 

### Call-outs:

1. There might be a more robust way of showing the full log to the user but till then, we are throwing the full stderr into the popup window.

### Testing:

* How is this change tested? Manual

* Is this a refactor change?

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/model/kaniRunner.ts [hunk 1]
```diff
@@ -159,6 +169,13 @@ function executeKaniProcess(
 				error: error,
 			};
 
+			// Send output to diagnostics and return if there is an error in stdout
+			// this means that the command could not be executed.
+			if(stdout.includes("error") && stderr.includes("error"))
```
Comment (karkhaz) [inline src/model/kaniRunner.ts]: Is this the test that checks whether Kani crashed as opposed to failing a harness?

If so, I'm not sure I agree. Kani might crash before printing any output at all. Also 'error' is a perfectly legitimate string that can appear in stdout/stderr without a crash, sometimes a file might be called `error.rs` or it might appear in the name of a harness.

Would it work if you instead check for a particular string that Kani is supposed to print out, rather than one that it is not supposed to print out? My suggestion is: check for the string `VERIFICATION:-` which CBMC prints out right at the end. If you see that string, Kani hasn't crashed.

Honestly a better idea would be for Kani to have a set of known return codes, and if you don't see any of them, then assume a crash. For example, CBMC returns 0 on success, 10 if a harness fails, 6 when it crashes, etc. We're also thinking about a structured output for Kani so that there's no need to parse strings. But for now, I think checking for `VERIFICATION:- SUCCESSFUL` or `VERIFICATION:- FAILED` should be adequate.

Comment (jaisnan) [reply src/model/kaniRunner.ts]: Can do! Thanks for the idea, will work that in here.

File: src/model/kaniOutputParser.ts [hunk 2]
```diff
@@ -49,6 +49,20 @@ class CheckInstance {
 	}
 }
 
+// Check if stderr and std out contain the error strings or the strings indicating successful compilation and verification
+export function checkOutputForError(outString: string, errString: string): boolean {
+	if (errString.includes('Finished dev') && outString.includes('VERIFICATION:-')) {
```
Comment (jaisnan) [inline src/model/kaniOutputParser.ts:54]: It still feels fragile honestly, I can try to add additional checks but need some ideas @karkhaz .

Comment (karkhaz) [reply src/model/kaniOutputParser.ts:54]: I think this is actually okay. I'm not sure that the if statement below is necessary. I think this entire function could be `return outString.includes('VERIFICATION:-')`

**Review by karkhaz — APPROVED** [review]
