### PR TITLE
Patch broken report finding

### LINKED ISSUE #5: Fix broken viewer report finding for bolero cases
I tried this: For harnesses run under #[test], the viewer report doesn't always show up as the --visualize option and the function to find the report are async with each other.

### PR DESCRIPTION
**Pull request by jaisnan**
### Description of changes: 

The report generated by CBMC Viewer using the --visualize is stored in the target directory in the user's crate. For a given harness, the process of generating the report in the extension can be triggered by clicking on the "view report" link provided in the error UI (picture shown below shows the link). 

The process itself was fairly ad-hoc and relied on naively searching for all the paths in the target directory containing the given harness's name in their path. There were 2 sub processes, 1. run the visualize command and generate report, 2. run the python command that serves the report's html file on a server. These processes were async with each other.

This total process broke frequently for 3 reasons -

1. The path finding itself was fairly broken i.e there can be scenarios where there are multiple directories which contain the same harness name even within the target directory where CBMC viewer stores the generated report.
2. The process for generating the report was done locally through the user's terminal. While this has the advantage of continuously updating the user with the status of the process, it has the disadvantage that the process is entirely on the user's side, which meant it wasn't possible to chain this process with the server process.
3. The process for generating the report was async with the process for starting the server and displaying the report on the browser.

This fix addresses both of these issues by using Kani's output and relying on Kani's output to find the path for the report. Almost all the cases that broke frequently now display the report as expected.
 
Screen Shot 2023-01-20 at 7 45 37 PM
Screen Shot 2023-01-20 at 7 45 11 PM
why this change is necessary.

### Resolved issues:

Resolves #5

### Call-outs:

1. As explained above, the change removes the process being run on the terminal, which means the user can be left waiting for the process to end before being updated with more information. For now, a brief pop up window displays that the process is being run in the background. However, in a future update, this needs to be fixed by showing a progress window to the user.

2. The underlying output that is being parsed is not the most reliable output, and if this process is to be stabilized, an API from Kani's side for the file output needs to be provided.

### Testing:

* How is this change tested? Manual testing against multiple harness scenarios

* Is this a refactor change? Yes

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/ui/reportView/callReport.ts [hunk 1]
```diff
@@ -36,37 +44,31 @@ export async function callViewerReport(
...
 	const filename: string = harnessName;
-
-	// Replace timeout with await for the final commmand to finish running
-	await setTimeout(5000);
-	const pythonCommand: string = `python3 -m http.server --directory`;
-
-	const filePath: string = findPath(searchDir, filename);
-	if (!filePath) {
+	const filePath: string = await findPath(searchDir, filename);
+	if (!filePath || filePath === '') {
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:66]: `!filePath` is not possible

File: src/ui/reportView/callReport.ts [hunk 2]
```diff
@@ -96,7 +98,7 @@ function createCommand(commandURI: string, harnessFile: string, harnessName: str
 }
 
 // 	Find the path of the report from the harness name
-function findPath(dir: string, filename: string): string {
+async function findPath(dir: string, filename: string): Promise<string> {
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:101]: why has this been changed to `async`?

File: src/ui/reportView/callReport.ts [hunk 3]
```diff
@@ -114,3 +116,45 @@ function findPath(dir: string, filename: string): string {
 
 	return '';
 }
+
+/**
+ * Run the visualize command to generate the report, parse the output to return the python server command and status
+ *
+ * @param command - the cargo kani | kani command to run --visualize
+ * returns - A promise of the python command and the status code; Promise<visualizeOutput>
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:124]: `@returns`

File: src/ui/reportView/callReport.ts [hunk 4]
```diff
@@ -114,3 +116,45 @@ function findPath(dir: string, filename: string): string {
...
+ */
+async function runVisualizeCommand(command: string): Promise<visualizeOutput> {
+	try{
+		vscode.window.showWarningMessage("Generating viewer report");
+		const {stdout, stderr} = await execPromise(command);
+		const serveReportCommand = await parseReportOutput(stdout);
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:130]: typing

File: src/ui/reportView/callReport.ts [hunk 5]
```diff
@@ -114,3 +116,45 @@ function findPath(dir: string, filename: string): string {
...
+		// console.error(`stderr: ${stderr}`);
+
+		return {statusCode: 0, serverCommand: serveReportCommand};
+	} catch (error) {
+		console.error(`exec error: ${error}`);
+		return {statusCode: 0, serverCommand: ''};
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:136]: should a caught error return a status code that does not imply success?

File: src/ui/reportView/callReport.ts [hunk 6]
```diff
@@ -114,3 +116,45 @@ function findPath(dir: string, filename: string): string {
...
+}
+
+/**
+ * Search for the python command contained in Kani's output and throw it onto the user's terminal
+ *
+ * @param stdout - kani stdout output that contains the full python command to be run by the terminal
+ * returns - python command that looks like "python3 -m http.server --path path"
+ */
+async function parseReportOutput(stdout: string): Promise<string> {
+	const kaniOutput = stdout;
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:147]: typings in the method

File: src/ui/reportView/callReport.ts [hunk 7]
```diff
@@ -114,3 +116,45 @@ function findPath(dir: string, filename: string): string {
...
+	const kaniOutputArray = kaniOutput.split("\n");
+	const searchString = "python3";
+
+	for(const outputString of kaniOutputArray){
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:151]: spacing in the `for` and the `if`; typing inside the block

File: src/ui/reportView/callReport.ts (hunk 5 above)
Comment (jaisnan) [reply src/ui/reportView/callReport.ts:136]: No, it makes for better design if I changed the statuscode to return 1 when there is an error, I'll need to change the handling maybe for it but I can see how it's more sensible.

File: src/ui/reportView/callReport.ts (hunk 2 above)
Comment (jaisnan) [reply src/ui/reportView/callReport.ts:101]: I wanted the function to be blocking, without verifying that the path exists in the target directory, i do not want the link to view the file to be created and presented to the user. There are issues where the underlying project that creates the report or kani can be slow with generating the report and in that case, I think it would create for a better UX to not create a link than to create a broken link.

File: src/ui/reportView/callReport.ts [hunk 8]
```diff
@@ -95,22 +104,74 @@ function createCommand(commandURI: string, harnessFile: string, harnessName: str
...
+ * Run the visualize command to generate the report, parse the output to return the python server command and status
+ *
+ * @param command - the cargo kani | kani command to run --visualize
+ * @returns - A promise of the python command and the status code; Promise<visualizeOutput>
+ */
+async function runVisualizeCommand(command: string, harnessName: string): Promise<visualizeOutput> {
+	try {
+		vscode.window.showInformationMessage(`Generating viewer report for ${harnessName}`);
+		const { stdout, stderr } = await execPromise(command);
+		const serveReportCommand: string = await parseReportOutput(stdout);
```
Comment (quaeler) [inline src/ui/reportView/callReport.ts:117]: nit - i think you meant `serverReportCommand` instead of `serveReportCommand` — not worth another revision

**Review by quaeler — APPROVED** [review]
