### PR TITLE
Fix `View report` feature to work in local and remote environments

### LINKED ISSUE #35: Parsing the output while looking for path to report shouldn't rely on Python command
The function `parseReportOutput` looks for the `python3` substring when searching for the path to the report. However, that string doesn't actually get printed unless you're executing VSCode in a remote machine. This is what the code in Kani looks like:

```rust
       if !self.args.quiet {
            println!("Report written to: {}/html/index.html", report_dir.to_string_lossy());
            warning("coverage information has been disabled for `--visualize` reports");
            // If using VS Code with Remote-SSH, suggest an option for remote viewing:
            if std::env::var("VSCODE_IPC_HOOK_CLI").is_ok()
                && std::env::var("SSH_CONNECTION").is_ok()
            {
                println!(
                    "VS Code automatically forwards ports for locally hosted servers. To view the report remotely,\nTry:  python3 -m http.server --directory {}/html",
                    report_dir.to_string_lossy()
                );
            }
        }
```

The extension feature should rely on the "Report written..." string instead.

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Currently, the extension relies on a Python command that is printed in Kani's output to get the path to the report. However, this command is only printed if Kani is being executed in remote computer through SSH. Because of that, the "View report" feature doesn't work as expected in a local environment.

This PR fixes these issues by searching for the path in another string contained in Kani's output which is always printed. It goes further by detecting if the extension is being executed in a local or remote environment. In a local environment, it will show a window to open the report in a browser. In a remote one, it will do the same it was doing until now (i.e., run a command that start an HTTP server through terminal, which automatically shows a message to open it in a browser).

The window that opens the report in a browser (in a local environment):
Screen Shot 2023-02-16 at 12 12 02

### Resolved issues:

Resolves #35 

### Testing:

* How is this change tested? Manually on both local and remote environments.

* Is this a refactor change? No, but it also contains refactoring changes (for showing errors or results).

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

File: src/ui/reportView/callReport.ts [hunk 1]
```diff
@@ -109,54 +146,64 @@ function createCommand(
...
 	const kaniOutput: string = stdout;
 	const kaniOutputArray: string[] = kaniOutput.split('\n');
-	const searchString: string = 'python3';
+	const searchString: string = 'Report written to:';
 
 	for (const outputString of kaniOutputArray) {
-		if (outputString.includes(searchString)) {
-			const command: string = outputString.split(searchString)[1];
+		if (outputString.startsWith(searchString)) {
+			const reportPath: string = outputString.split(' ')[3]
```
Comment (karkhaz) [inline src/ui/reportView/callReport.ts:186]: Paths can contain spaces, especially on windows. Since the beginning of the string is known constant, I suggest

```js
const reportPath: string = outputString.substring(searchString.length)
```

File: src/ui/reportView/callReport.ts [hunk 2]
```diff
@@ -18,9 +18,16 @@ interface htmlMetaData {
 	searchDir: string;
 }
 
+interface visualizeResult {
```
Comment (jaisnan) [inline src/ui/reportView/callReport.ts:21]: `visualizeResult` is too similar to `visualizeOutput` by name but they talk about different things. I'd rename visualizeResult to `ReportMetadata` I think.

File: src/ui/reportView/callReport.ts [hunk 3]
```diff
@@ -109,54 +146,64 @@ function createCommand(
...
-			const filePathExists: boolean = await checkPathExists(command);
+			// Check if the path exists as expected
+			const filePathExists: boolean = await checkPathExists(reportPath);
 			if (!filePathExists) {
-				return '';
+				return undefined;
+			}
+
+			// Determine if the environment is remote
+			if (process.env.SSH_CONNECTION !== undefined) {
```
Comment (jaisnan) [inline src/ui/reportView/callReport.ts:195]: Nice!

File: src/ui/reportView/callReport.ts [hunk 4]
```diff
@@ -109,54 +146,64 @@ function createCommand(
...
+ * @returns - the result of executing the visualize command and parsing the output
  */
 async function runVisualizeCommand(command: string, harnessName: string): Promise<visualizeOutput> {
 	try {
 		vscode.window.showInformationMessage(`Generating viewer report for ${harnessName}`);
 		const { stdout, stderr } = await execPromise(command);
-		const serveReportCommand: string = await parseReportOutput(stdout);
-		if (serveReportCommand === '') {
-			return { statusCode: 2, serverCommand: stderr };
+		const parseResult = await parseReportOutput(stdout);
```
Comment (jaisnan) [inline src/ui/reportView/callReport.ts:158]: I think there's some value in directly displaying the stderr to the user so they know what's causing the crash. Thoughts?

**Review by jaisnan — CHANGES_REQUESTED** [review]

**Review by jaisnan — APPROVED** [review]
Didn't mean to make those comments blocking. LGTM overall.

File: src/ui/reportView/callReport.ts (hunk 1 above)
Comment (adpaco-aws) [reply src/ui/reportView/callReport.ts]: Right, didn't think about that! Changed to use `substring` (one space added to the end of `searchString` so we don't need to trim `reportPath`).

File: src/ui/reportView/callReport.ts (hunk 2 above)
Comment (adpaco-aws) [reply src/ui/reportView/callReport.ts:21]: Agree, changed to `reportMetadata`.

File: src/ui/reportView/callReport.ts (hunk 4 above)
Comment (adpaco-aws) [reply src/ui/reportView/callReport.ts:158]: Good catch, thanks! I didn't notice I could pass `stderr` when I refactored this code.

**Review by jaisnan — APPROVED** [review]
Looks great! Thanks!
